# It's backwards root.
- name: Add group
  group:
    name: toor
    state: present

- name: Add user
  user:
    name: toor
    group: toor
    shell: /bin/bash
    home: /home/toor
    create_home: yes
    state: present

- name: Add SSH public key for user
  authorized_key:
    user: toor
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
