name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

  
jobs:
  ansible:
    name: ansible
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: site.yaml
          directory: ./
          options: |
            --check
